In [17]:
# Import necessary libraries
from astropy.table import Table
import pandas as pd

# Define the file path
file_path = r"C:\git_repo\cool-dwarf_stellar_parameter_inference_from_survey_data\data\LAMOST_data\LAMOST_K0-7.vot"

# Read the .vot file using astropy
votable = Table.read(file_path, format='votable')

# Convert to pandas DataFrame
dataframe = votable.to_pandas()

# Display the first few rows of the DataFrame
dataframe.head()

   COLID_92974 COLID_92992          COLID_93001
0       101002          K7  2676109292239283200
1       101014          K5  2676110426110666496
2       101016          K3  2676107368093944576
3       101024          K5  2676868844320528384
4       101032          K5  2676937327574051712

In [2]:
dataframe.columns

Index(['COLID_92974', 'COLID_92992', 'COLID_93001'], dtype='object')

In [12]:
dataframe.head()

        gaia_source_id
0  1192528632157238784
1  1192594156178353920
2  1192574674206669824
3  1192584535451587840
4  1192581511794617088